version: "3.5"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=error
    ports:
      - published: 9090
        target: 9090
    volumes:
      - type: bind
        source: ./deployment/prometheus/config.yml
        target: /etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana:9.5.2
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - published: 8085
        target: 3000
    volumes:
      - type: bind
        source: ./deployment/grafana/dashboards
        target: /var/lib/grafana/dashboards
      - type: bind
        source: ./deployment/grafana/provisioning/dashboards
        target: /etc/grafana/provisioning/dashboards
      - type: bind
        source: ./deployment/grafana/provisioning/datasources
        target: /etc/grafana/provisioning/datasources
      - type: bind
        source: ./deployment/grafana/grafana.ini
        target: /etc/grafana/grafana.ini
    depends_on:
      - prometheus
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI port
      - "4317:4317" # the open telemetry grpc port for sending traces
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=error
